AY2223S1-CS2103T-W08-4/tp

docs/team/hauchongtang.md
Skeletal PPP required for contribution tracking and documentation.
As per specification, only markdown format for now.
=> Add Skeletal PPP

docs/UserGuide.md
Content is slightly proofread and edited to match markdown format.
Images have yet to be added.
=> Import user guide from draft

docs/UserGuide.md, docs/_config.yml, docs/_sass/minima/_base.scss
Updated settings to fit Salsey's repo as much as possible
=> Update Jekyll site-wide settings

docs/UserGuide.md
=> Attempt fix for UG TOC

src/main/java/seedu/address/ui/MainWindow.java, src/main/java/seedu/address/ui/TaskListPanel.java, src/main/resources/view/MainWindow.fxml, src/main/resources/view/TaskListCard.fxml, src/main/resources/view/TaskListPanel.fxml
Changes are currently skeletal
Task class has not been created yet
Requires adaptation to Task class once it is completed
=> Add SplitView feature for GUI

src/main/java/seedu/address/MainApp.java, src/main/java/seedu/address/logic/Logic.java, src/main/java/seedu/address/logic/LogicManager.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/ReadOnlyTaskList.java, src/main/java/seedu/address/model/TaskList.java, src/main/java/seedu/address/model/task/Task.java, src/main/java/seedu/address/model/util/SampleDataUtil.java, src/main/java/seedu/address/storage/JsonAdaptedTask.java, src/main/java/seedu/address/storage/JsonSerializableTaskList.java, src/main/java/seedu/address/storage/JsonTaskStorage.java, src/main/java/seedu/address/storage/Storage.java, src/main/java/seedu/address/storage/StorageManager.java, src/main/java/seedu/address/storage/TaskStorage.java, src/main/java/seedu/address/ui/MainWindow.java, src/main/java/seedu/address/ui/TaskCard.java, src/main/java/seedu/address/ui/TaskListPanel.java, src/main/resources/view/TaskListCard.fxml, src/test/java/seedu/address/logic/commands/AddCommandTest.java, src/test/java/seedu/address/testutil/TaskBuilder.java
```
// file name --> data\\tasklist.json
{
"tasks": [ {
"title": "Replenish ginger",
"deadline": "29 Oct 2029",
"tagged": ["Food", "Action"]
}, {
"title": "Buy Gas",
"deadline": "10 Oct 2023",
"tagged": ["Fuel"]
},{
"title": "Buy Gas",
"deadline": "10 Oct 2023",
"tagged": ["Fuel"]
}, {
"title": "Buy Noodles",
"deadline": "10 Oct 2023",
"tagged": ["Food", "Action"]
} ]
}
```
=> Feature skeletal task data

src/main/resources/view/DarkTheme.css, src/main/resources/view/MainWindow.fxml
Adapt status bar to Salesy theme
=> Add headers to both Task and Supplier panes

src/main/java/seedu/address/commons/core/Messages.java, src/main/java/seedu/address/logic/LogicManager.java, src/main/java/seedu/address/logic/commands/MarkTaskCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/MarkTaskCommandParser.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/TaskList.java, src/main/java/seedu/address/model/task/Task.java, src/main/java/seedu/address/model/util/SampleDataUtil.java, src/main/java/seedu/address/storage/JsonAdaptedTask.java, src/main/java/seedu/address/storage/JsonSerializableTaskList.java, src/main/java/seedu/address/storage/JsonTaskStorage.java, src/main/java/seedu/address/ui/TaskCard.java, src/main/resources/view/DarkTheme.css, src/main/resources/view/MainWindow.fxml, src/main/resources/view/TaskListCard.fxml, src/test/java/seedu/address/logic/commands/AddCommandTest.java, src/test/java/seedu/address/logic/commands/MarkTaskCommandTest.java, src/test/java/seedu/address/logic/parser/AddressBookParserTest.java, src/test/java/seedu/address/logic/parser/MarkTaskCommandParserTest.java, src/test/java/seedu/address/storage/JsonAdaptedTaskTest.java, src/test/java/seedu/address/storage/StorageManagerTest.java, src/test/java/seedu/address/testutil/TaskBuilder.java, src/test/java/seedu/address/testutil/TestUtil.java, src/test/java/seedu/address/testutil/TypicalTasks.java
Add MarkTaskCommandTest and its accomoanying test utilities for unit tests
Add MarkTaskCommandParser to facilitate parsing of mark task command
Fix TaskStorage not saving to JSON
=> Add MarkTaskCommand for marking tasks as done

src/main/java/seedu/address/model/TaskList.java
Switch from List to ObservableList in TaskList
- Tested on addCommand branch
- Tested on markCommand as well.
- We might need to create a `UniqueTasksList` similar to `UniquePersonsList` but will not be complicated.
=> Fix the issue where TaskList's ObservableList is not updating

src/main/java/seedu/address/model/util/SampleDataUtil.java
Edited SampleDataUtil to adapt to Suppliers and added Supplier tag
=> Edited SampleDataUtil to adapt to Suppliers and added Supplier tag

src/main/java/seedu/address/logic/Logic.java, src/main/java/seedu/address/logic/commands/AddCommand.java, src/main/java/seedu/address/logic/commands/DeleteCommand.java, src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/logic/commands/FindCommand.java, src/main/java/seedu/address/logic/commands/ListCommand.java, src/main/java/seedu/address/model/person/Address.java, src/main/java/seedu/address/model/person/Item.java, src/main/java/seedu/address/model/person/Name.java, src/main/java/seedu/address/model/person/Person.java, src/main/java/seedu/address/model/person/Phone.java, src/main/java/seedu/address/model/person/Price.java, src/main/java/seedu/address/model/person/UniquePersonList.java, src/main/java/seedu/address/model/util/SampleDataUtil.java, src/test/java/seedu/address/model/person/PersonTest.java
IsSamePerson now returns if person has same name or phone number 
PersonTest cases also adapted to new isSamePerson function
=> Edited IsSamePerson and adapted PersonTest cases

docs/index.md, src/main/java/seedu/address/model/person/Item.java, src/main/java/seedu/address/model/person/Price.java, src/test/java/seedu/address/model/person/ItemTest.java, src/test/java/seedu/address/model/person/PriceTest.java
New Testcases added for Price and Item 
All supplier components now covered for test cases
Item class now edited to take in strings and numbers but cannot take in numbers only
=> Add PriceTest and ItemTest files and cases

docs/UserGuide.md
Still unsure about the task commands
=> Edited UG to match Supplier commands

src/test/java/seedu/address/logic/commands/AddTaskCommandTest.java, src/test/java/seedu/address/logic/commands/CommandTestUtil.java, src/test/java/seedu/address/logic/parser/AddTaskCommandParserTest.java
Add testcase for AddTaskCommand class and AddTaskCommandParser class
=> Add testcase for AddTaskCommand class and AddTaskCommandParser class

src/main/java/seedu/address/logic/commands/DeleteTaskCommand.java, src/main/java/seedu/address/logic/commands/UpdateTaskCommand.java, src/main/java/seedu/address/logic/parser/UpdateTaskCommandParser.java, src/main/java/seedu/address/model/TaskList.java, src/main/java/seedu/address/model/task/Task.java, src/test/java/seedu/address/logic/commands/CommandTestUtil.java, src/test/java/seedu/address/logic/commands/DeleteTaskCommandTest.java, src/test/java/seedu/address/logic/commands/UpdateTaskCommandTest.java, src/test/java/seedu/address/logic/parser/AddressBookParserTest.java, src/test/java/seedu/address/logic/parser/DeleteTaskCommandParserTest.java, src/test/java/seedu/address/logic/parser/UpdateTaskCommandParserTest.java, src/test/java/seedu/address/model/task/TaskListTest.java, src/test/java/seedu/address/model/task/TaskTest.java, src/test/java/seedu/address/testutil/UpdateTaskDescriptorBuilder.java
Improved test cases for other Task components.
=> Added test case for Delete and Update task command

src/main/java/seedu/address/model/Inventory.java, src/main/java/seedu/address/model/item/SupplyItem.java, src/test/java/seedu/address/model/item/InventoryTest.java, src/test/java/seedu/address/model/item/SupplyItemTest.java
Condition for Supplyitem name changed to match the condition for item in person field 
Yet to implement checks for matching Supplyitem name and person item
But test cases for current SupplyItem and Inventory classes
=> Test classes for SuppyItem and Inventory classes added

src/main/java/seedu/address/logic/commands/FindCommand.java, src/main/java/seedu/address/logic/parser/FindCommandParser.java, src/main/java/seedu/address/model/person/ItemContainsKeywordsPredicate.java, src/test/java/seedu/address/logic/parser/AddressBookParserTest.java, src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
Find command now can search by either name OR item. Choose with prefix n/ or i/
Will add more test cases later
=> Update supplier find command

src/main/java/seedu/address/logic/parser/AddTaskCommandParser.java, src/test/java/seedu/address/logic/commands/AddTaskCommandTest.java, src/test/java/seedu/address/logic/parser/AddTaskCommandParserTest.java
Update test cases to check parsing is successful when tag is optional
=> Refactor code for tag to be optional for addTask

src/main/java/seedu/address/commons/util/StockUtil.java, src/main/java/seedu/address/ui/MainWindow.java, src/main/java/seedu/address/ui/StatsCard.java, src/main/java/seedu/address/ui/SupplyItemCard.java, src/main/resources/view/DarkTheme.css, src/main/resources/view/MainWindow.fxml, src/main/resources/view/StatsCard.fxml, src/main/resources/view/TaskListCard.fxml, src/test/java/seedu/address/commons/util/StockUtilTest.java
1. Fixes fatal bug #140 
2. Add a Stats Pane with relevant information
* Inventory Status (RED, ORANGE, GREEN)
* Tasks Status
* Number of incomplete tasks
* Earliest Task to be due. (Might want to enforce date checks, i.e. only date that fall on today onwards are allowed.)
=> Add information to Stats panel

src/main/java/seedu/address/MainApp.java, src/main/java/seedu/address/ui/StatsCard.java
=> Add safer handling to method

src/main/java/seedu/address/logic/commands/AddItemCommand.java, src/main/java/seedu/address/logic/parser/AddItemCommandParser.java, src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json, src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json, src/test/data/JsonSerializableInventoryTest/typicalInventory.json, src/test/java/seedu/address/logic/commands/AddItemCommandTest.java, src/test/java/seedu/address/logic/commands/FindCommandTest.java, src/test/java/seedu/address/logic/parser/AddItemCommandParserTest.java, src/test/java/seedu/address/testutil/TypicalPersons.java
Also changed TypicalPerson data to resemble suppliers
=> Added Test cases for AddItemCommand and AddItemCommandParser

src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/logic/commands/EditItemSupplierCommand.java, src/test/java/seedu/address/logic/commands/EditItemSupplierCommandTest.java
Squashed bug where the SupplyItem linked to a supplier is not updated when that supplier's name and phone are both edited in 1 command
=> Fix bug in edit command

src/main/java/seedu/address/ui/InventoryPanel.java, src/main/java/seedu/address/ui/SupplyItemCard.java, src/main/resources/view/SupplyItemCard.fxml
Refer to #161 for more information.
=> Fix for Ui bug regarding elipsis due to initial onAction

src/main/java/seedu/address/logic/LogicManager.java, src/main/java/seedu/address/ui/SupplyItemCard.java, src/main/resources/view/SupplyItemCard.fxml
Add a listener to prevent user from inputting more than 5 digits to textfield
=> Change default action of TextField to resemble form submission

src/main/java/seedu/address/MainApp.java, src/main/java/seedu/address/model/util/SampleDataUtil.java, src/main/java/seedu/address/ui/StatsCard.java, src/main/java/seedu/address/ui/SupplyItemCard.java
Refer to issue here #166 
Handle exceptions with try catch block and log the exception in logger.
Update sample data in `SampleDataUtil` to prepare for v1.3b launch
=> Revert back to NFE exception handling

docs/UserGuide.md
* Minor UG bug: Command missing correct format.
=> Fix for minor UG bug

docs/UserGuide.md
Update UG to show task can have multiple tags
=> Update UG to show task can have multiple tags

docs/UserGuide.md
Added an `Important Information` section to put important prior knowledge before using the UG, please add on to it
=> Update UG to improve clarity

src/main/java/seedu/address/logic/commands/AddCommand.java, src/main/java/seedu/address/logic/commands/DeleteCommand.java, src/main/java/seedu/address/model/person/Name.java, src/main/java/seedu/address/model/person/Person.java, src/test/java/seedu/address/model/person/PersonTest.java
Fix for #194:
Typo in example add command is rectified
Fix for #198:
Check for duplicate supplier names is now case insensitive
Fix for #222:
Deleting supplier is blocked if the supplier is currently supplying a SupplyItem in inventory
=> Bug fixes for supplier related bugs

src/main/java/seedu/address/model/ModelManager.java
Fix bug where deleteTask does not work
=> Fix bug where deleteTask does not work

src/main/java/seedu/address/logic/parser/EditStockCommandParser.java, src/main/java/seedu/address/ui/PersonCard.java, src/main/java/seedu/address/ui/SupplyItemCard.java, src/main/java/seedu/address/ui/TaskCard.java, src/main/resources/view/PersonListCard.fxml, src/main/resources/view/SupplyItemCard.fxml, src/main/resources/view/TaskListCard.fxml
Fix bug for other potential field to have long text to enable word wrap
=> Fix bug where elipsis is shown due to long text

docs/UserGuide.md
Reordered some portions and made the formatting more consistent
=> Update formatting and grammar in UG

src/main/java/seedu/address/ui/UiManager.java, src/main/resources/view/MainWindow.fxml
1. Mac users report that the window starts too enlarged
2. Mac users are unable to resize their window
Hence is a functionality bug
=> Fix for contents being blocked on mac

docs/UserGuide.md
* Squash #263 
* Add drop down for items that has `more information`.
=> Refine UG and fix bugs

docs/UserGuide.md
Toggle dropdown does not work on PDF formats hence the revert
=> Hotfix ug formatting

docs/team/bahamas20.md, src/test/java/seedu/address/logic/parser/AddItemCommandParserTest.java
Help me merge first ill add more stuff later on
=> Rough PPP draft

docs/UserGuide.md, src/main/java/seedu/address/logic/commands/AddItemCommand.java, src/main/java/seedu/address/logic/commands/FindCommand.java, src/main/java/seedu/address/logic/parser/FindCommandParser.java
Added notes in user guide 
Fixed bugs in find command
=> Fix to bugs remaining

docs/UserGuide.md
* Page breaks to make the pdf view nicer
=> Add page breaks to optimize pdf view

docs/team/kang-quan.md
Fix format and numbering for PPP
=> Fix format and numbering for PPP

docs/team/kang-quan.md
=> Fix incorrect links in PPP

docs/team/kang-quan.md
=> Fix typo in link in PPP
